version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "20"
  jobs:
    post_install:
      # avoid the lengthy `typedoc` build inside `sphinx` for cleaner logs
      - jlpm
      - jlpm build:packages
      - jlpm build:docs

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
